### ISSUE TITLE
Käyttäjän pitäisi pystyä piirtämään

### ISSUE THREAD

**Issue by JaniL** [muhve/laulum.me#1]
>Jani L, [12.02.17 20:30]
>Meil on muuten hieno elektroninen laulukirja nykyään
>xxx, [12.02.17 20:40]
miten elektroniseen laulukirjaan voi piirtää kirkkoveneitä?
>Jani L, [12.02.17 20:40]
>hmm hyvä huomio
>Jani L, [12.02.17 20:40]
>pitää tehdä tästä issue

**Comment by neodyymi** [comment]
Jos lisätään painike tätä varten ja merkintä keksiin?

**Comment by JaniL** [comment]
Nappula josta tulee piirtomoodi päälle, sit sivun päälle laitetaan läpinäkyvä canvas johon piirretään ms paint-tussia toucheventeistä. Mallii voi ottaa snäpin piirtotyökaluista.

**Comment by muhve** [comment]
Voi juku :D
